services:
  unmanic-dev:
    container_name: unmanic-plugin-dev
    image: ghcr.io/unmanic/unmanic:staging
    userns_mode: keep-id
    command: ['/usr/bin/unmanic', '--port', '7888']
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    ports:
      - '7888:7888'
    volumes:
      - ./build:/config/.unmanic:z
